# Generated by Django 3.0.6 on 2020-05-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('ItemPrice', models.FloatField()),
                ('ItemColor', models.CharField(max_length=15)),
                ('ItemCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Image', models.ImageField(blank=True, default='No Image Found', null=True, upload_to='Images')),
                ('ContactNo', models.CharField(max_length=10)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderedItem', models.CharField(max_length=100)),
                ('OrderedDate', models.DateTimeField()),
                ('Total_Price', models.FloatField()),
                ('Description', models.TextField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.PersonalDetails')),
                ('Item_id1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.Items')),
            ],
        ),
    ]
